#unbranded ps3-style gamepad with usb dongle
teleop_twist_joy_node:
  ros__parameters:
    axis_linear:  
      x: 1        # axis for throttle
    scale_linear:
      x: 0.7
    scale_linear_turbo:
      x: 1.5

    axis_angular:  
      yaw: 0       # axis for turning
    scale_angular:
      yaw: 0.4
    # should be used if your controller has stick drift
    require_enable_button: true 
    enable_button: 6        # Left bumper to move
    enable_turbo_button: 7  # Right bumper to move fast