#unbranded ps3-style gamepad with usb dongle
teleop_twist_joy_node:
  ros__parameters:
    axis_linear:  
      x: 2        # axis for throttle
    scale_linear:
      x: -0.7    #used to be 0.7
    scale_linear_turbo:
      x: 1.5

    axis_angular:  #//Forward and Reverse
      yaw: 1       # axis for turning
    scale_angular:
      yaw: -2.0    #used to be 0.4
    scale_angular_turbo:
      yaw: 4.0
    # should be used if your controller has stick drift
    require_enable_button: true 
    enable_button: 9        # Left bumper to move
    enable_turbo_button: 8  # Right bumper to move fast